dist: focal
sudo: required
language: node_js
node_js:
  - "22"

services:
  - docker

before_install:
  - gem install nokogiri
  - gem install logger
  - docker build -t mpatal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mpatal/react-test npm test

after_success:
  - docker build -t mpatal/multi-client ./client
  - docker build -t mpatal/multi-nginx ./nginx
  - docker build -t mpatal/multi-server ./server
  - docker build -t mpatal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mpatal/multi-client
  - docker push mpatal/multi-nginx
  - docker push mpatal/multi-server
  - docker push mpatal/multi-worker